### ISSUE TITLE
The leaderboard is removed...

### ISSUE THREAD

**Issue by zhimin-z** [The-FinAI/PIXIU#78]
![image](https://github.com/user-attachments/assets/ec0b7a6f-d5c5-462f-8194-0f741c01ef98)
Check this linkage but found:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/6fe2e074-976b-432c-94a4-2a65faea254c">

**Comment by miragecoa** [comment]
We are currently transfering our leaderboard to FinOS. The leaderboard is currently at https://huggingface.co/spaces/TheFinAI/Open-Financial-LLM-Leaderboard. Will be transfered soon. We will update the link once it transfered .

**Comment by zhimin-z** [comment]
> We are currently transfering our leaderboard to FinOS. The leaderboard is currently at https://huggingface.co/spaces/TheFinAI/Open-Financial-LLM-Leaderboard. Will be transfered soon. We will update the link once it transfered .

Thus, these two leaderboards mentioned in https://github.com/The-FinAI/PIXIU/issues/79 are the same?

**Comment by miragecoa** [comment]
No big difference. The FinBen one will be removed soon.

**Comment by zhimin-z** [comment]
> No big difference. The FinBen one will be removed soon.

Thanks for clarification.

**Comment by zhimin-z** [comment]
Closed since the link is redirected to https://huggingface.co/spaces/finosfoundation/Open-Financial-LLM-Leaderboard correctly 👍
